### ISSUE TITLE
Python 3 failure.

### ISSUE THREAD

**Issue by Akado2009** [CiscoAI/amla#30]
Code sample:
```
git clone git@github.com:CiscoAI/amla.git
cd amla/amla
virtualenv -p python3.6 env
source env/bin/activate
pip install -r requirements.txt
python amla.py
```
Following erorr:
```
 (AttributeError: 'AmlaCLI' object has no attribute 'completekey’)
```

No app to be seen on localhost:5000 (Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.)

Funny thing:
if you try to start it again you get
```
Traceback (most recent call last):
  File "/Users/kprosvir/amla/amla/scheduler.py", line 335, in <module>
    scheduler.run()
  File "/Users/kprosvir/amla/amla/common/task.py", line 72, in run
    self.main()
  File "/Users/kprosvir/amla/amla/scheduler.py", line 74, in main
    self.app.run(host=self.host, port=self.port)
  File "/Users/kprosvir/amla/amla/env/lib/python3.6/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/Users/kprosvir/amla/amla/env/lib/python3.6/site-packages/werkzeug/serving.py", line 814, in run_simple
    inner()
  File "/Users/kprosvir/amla/amla/env/lib/python3.6/site-packages/werkzeug/serving.py", line 774, in inner
    fd=fd)
  File "/Users/kprosvir/amla/amla/env/lib/python3.6/site-packages/werkzeug/serving.py", line 660, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/Users/kprosvir/amla/amla/env/lib/python3.6/site-packages/werkzeug/serving.py", line 577, in __init__
    self.address_family), handler)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
    self.server_bind()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
```

In order to fix: ps -e | grep python. Find a process with scheduler -> kill it.

**Comment by tremblerz** [comment]
Sorry for getting late on this.
@Akado2009 are you sure `pip install -r requirements.txt` work for you? It requires some dependency like mysql-dev and etc. It might be possible that it does not connect to DB in the first place.
Also, what OS and version are you using? I just now tried with new dockerfile with Ubuntu 16.04 and followed same commands as mentioned by you and it worked as expected.
